### ISSUE TITLE
cannot find "internal" packages

### ISSUE THREAD

**Issue by bedis** [open-policy-agent/example-api-authz-go#5]
Hi,

When I try to do the `go build` command, it seems that go can't find the packages in the local internal folder.
I tried to set GOPATH to $PWD or to rename path to internal/api in the main.go file, without any success.
Help would be welcome.

**Comment by ashutosh-narkar** [comment]
What version of Go are you using ? Also is your GO setup working for other Go programs ?

**Comment by bedis** [comment]
I am using "go version go1.12 linux/amd64" and yes, I already built and compiled some other go softwares

**Comment by ashutosh-narkar** [comment]
Was there any build error ? If yes, can you paste the output ?

**Comment by bedis** [comment]
Closing.
I finally realized this was not the way I wanted to use OPA and did it using the OPA go library directly
