### ISSUE TITLE
About "authz.tar.gz"

### ISSUE THREAD

**Issue by quaintclever** [open-policy-agent/example-api-authz-go#9]
Do I need to start a service and return the "authz.tar.gz" file by calling the following interface?
https://example.com/control-plane/api/v1/bundles/http/example/authz.tar.gz

But I didn't find this "authz.tar.gz" in the repositories. How should I write it.
I just started to learn opa. It's a little vague. Can you add an example?

**Comment by anderseknert** [comment]
Hi @quaintclever! You could build the bundle on your machine with `opa build --bundle policy/` or wherever you've chosen to store your policy. If you just want to test something quickly I'd recommend serving the bundle from a local nginx, as described in the OPA docs in most of the tutorials (for example [here](https://www.openpolicyagent.org/docs/latest/http-api-authorization/)).

**Comment by quaintclever** [comment]
Thank you very much. It solves my question
